apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kiran-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kiran-app
    spec:
      containers:
      imagePullSecrets:
      - name: docker-hub  
      - image: ashutosh1710204/kiran-app:latest
        name: kiran-app
        env:
        - name: MYSQL_HOST
          value: mysql
        ports:
        - containerPort: 5000
          name: kiran-app
  replicas: 1
